package com.oracle.huabing.model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 25 14:02:21 CST 2015
// ---------------------------------------------------------------------
public interface DepartmentEOViewRow extends Row {
    Integer getDepartmentId();

    void setDepartmentId(Integer value);

    String getDepartmentName();

    void setDepartmentName(String value);

    Integer getManagerId();

    void setManagerId(Integer value);

    Integer getLocationId();

    void setLocationId(Integer value);
}

