package com.oracle.huabing.model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 24 17:14:55 CST 2015
// ---------------------------------------------------------------------
public interface HRServiceAppModule extends ApplicationModule {
    void setDepartmentName(String name);
}

