package com.oracle.huabing.model.view;

import com.oracle.huabing.model.entity.DepartmentEOImpl;
import com.oracle.huabing.model.view.common.DepartmentEOViewRow;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 25 14:02:19 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentEOViewRowImpl extends ViewRowImpl implements DepartmentEOViewRow {


    public static final int ENTITY_DEPARTMENTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        DepartmentId,
        DepartmentName,
        ManagerId,
        LocationId,
        Guid,
        EmployeeEOView,
        LocationsView1,
        EmployeeEOView1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int GUID = AttributesEnum.Guid.index();
    public static final int EMPLOYEEEOVIEW = AttributesEnum.EmployeeEOView.index();
    public static final int LOCATIONSVIEW1 = AttributesEnum.LocationsView1.index();
    public static final int EMPLOYEEEOVIEW1 = AttributesEnum.EmployeeEOView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentEOViewRowImpl() {
    }

    /**
     * Gets DepartmentEO entity object.
     * @return the DepartmentEO
     */
    public DepartmentEOImpl getDepartmentEO() {
        return (DepartmentEOImpl) getEntity(ENTITY_DEPARTMENTEO);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(Integer value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @return the DEPARTMENT_NAME
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @param value value to set the DEPARTMENT_NAME
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public Integer getManagerId() {
        return (Integer) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
    public void setManagerId(Integer value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LocationId.
     * @return the LOCATION_ID
     */
    public Integer getLocationId() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
     * @param value value to set the LOCATION_ID
     */
    public void setLocationId(Integer value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for GUID using the alias name Guid.
     * @return the GUID
     */
    public String getGuid() {
        return (String) getAttributeInternal(GUID);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeeEOView.
     */
    public RowIterator getEmployeeEOView() {
        return (RowIterator) getAttributeInternal(EMPLOYEEEOVIEW);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LocationsView1.
     */
    public RowSet getLocationsView1() {
        return (RowSet) getAttributeInternal(LOCATIONSVIEW1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EmployeeEOView1.
     */
    public RowSet getEmployeeEOView1() {
        return (RowSet) getAttributeInternal(EMPLOYEEEOVIEW1);
    }
}

