package com.oracle.huabing.model.service;

import com.oracle.huabing.model.service.common.HRServiceAppModule;
import com.oracle.huabing.model.view.DepartmentEOViewImpl;
import com.oracle.huabing.model.view.common.DepartmentEOViewRow;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 24 17:12:00 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HRServiceAppModuleImpl extends ApplicationModuleImpl implements HRServiceAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public HRServiceAppModuleImpl() {
    }
    
    public void setDepartmentName(String name) {
        ((DepartmentEOViewRow)getDepartmentEOView1().getCurrentRow()).setDepartmentName(name);
        this.getTransaction().commit();
    }
    /**
     * Container's getter for DepartmentEOView1.
     * @return DepartmentEOView1
     */
    public DepartmentEOViewImpl getDepartmentEOView1() {
        return (DepartmentEOViewImpl) findViewObject("DepartmentEOView1");
    }

    /**
     * Container's getter for EmployeeEOView1.
     * @return EmployeeEOView1
     */
    public ViewObjectImpl getEmployeeEOView1() {
        return (ViewObjectImpl) findViewObject("EmployeeEOView1");
    }

    /**
     * Container's getter for DepartmentEOView2.
     * @return DepartmentEOView2
     */
    public DepartmentEOViewImpl getDepartmentEOView2() {
        return (DepartmentEOViewImpl) findViewObject("DepartmentEOView2");
    }

    /**
     * Container's getter for EmployeeEOView2.
     * @return EmployeeEOView2
     */
    public ViewObjectImpl getEmployeeEOView2() {
        return (ViewObjectImpl) findViewObject("EmployeeEOView2");
    }

    /**
     * Container's getter for EmployeeEOView3.
     * @return EmployeeEOView3
     */
    public ViewObjectImpl getEmployeeEOView3() {
        return (ViewObjectImpl) findViewObject("EmployeeEOView3");
    }

    /**
     * Container's getter for DeptMgrFkLink1.
     * @return DeptMgrFkLink1
     */
    public ViewLinkImpl getDeptMgrFkLink1() {
        return (ViewLinkImpl) findViewLink("DeptMgrFkLink1");
    }

    /**
     * Container's getter for EmpManagerFkLink1.
     * @return EmpManagerFkLink1
     */
    public ViewLinkImpl getEmpManagerFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpManagerFkLink1");
    }

    /**
     * Container's getter for EmpDeptFkLink1.
     * @return EmpDeptFkLink1
     */
    public ViewLinkImpl getEmpDeptFkLink1() {
        return (ViewLinkImpl) findViewLink("EmpDeptFkLink1");
    }

    /**
     * Container's getter for LocationsView1.
     * @return LocationsView1
     */
    public ViewObjectImpl getLocationsView1() {
        return (ViewObjectImpl) findViewObject("LocationsView1");
    }
}

